server:
  port: 8010
  servlet:
    context-path: /api/user
spring:
  profiles:
    active: dev
  application:
    name: ai-data-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/ai_data_etl_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated # 开启发送确认
    publisher-returns: true            # 开启发送失败返回
# ======================================================
jwt:
  secret: ai-data-etl-platform-jwt-secret-key-2025-spring-cloud
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: false
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.yuan.model.entity
  mapper-locations: classpath:mapper/*.xml
knife4j:
  enable: true