server:
  port: 8030

spring:
  application:
    name: ai-data-intelligence
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
        namespace: ${NACOS_NAMESPACE}
        group: ${NACOS_GROUP}
