server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
    name: ai-data-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ai-data-user
          uri: lb://ai-data-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: ai-data-intelligence
          uri: lb://ai-data-intelligence
          predicates:
            - Path=/api/intelligence/**
          filters:
            - StripPrefix=1
        - id: ai-data-monitor
          uri: lb://ai-data-monitor
          predicates:
            - Path=/api/monitor/**
          filters:
            - StripPrefix=1
jwt:
  secret: ai-data-etl-platform-jwt-secret-key-2025-spring-cloud
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
