# 端口配置
server:
  port: 8000
# 网关配置
spring:
  profiles:
    active: dev
  application:
    name: ai-data-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        # ==========================================
        #  user 服务openapi 文档
        # ==========================================
        - id: ai-data-user-openapi
          uri: lb://ai-data-user
          predicates:
            - Path=/v3/api-docs/ai-data-user/**
        # ==========================================
        # user 服务业务路由
        # ==========================================
        - id: ai-data-user
          uri: lb://ai-data-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        # ==========================================
        # intelligence 服务业务路由
        # ==========================================
        - id: ai-data-intelligence
          uri: lb://ai-data-intelligence
          predicates:
            - Path=/api/intelligence/**
          filters:
            - StripPrefix=1
        # ==========================================
        # monitor 服务业务路由
        # ==========================================
        - id: ai-data-monitor
          uri: lb://ai-data-monitor
          predicates:
            - Path=/api/monitor/**
          filters:
            - StripPrefix=1
# swagger 文档配置
knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
        - name: 用户服务
          url: /v3/api-docs/ai-data-user
          service-name: ai-data-user
          order: 1
# jwt 配置
jwt:
  secret: ai-data-etl-platform-jwt-secret-key-2025-spring-cloud