server:
  port: 8040

spring:
  application:
    name: ai-data-monitor
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
  boot:
    admin:
      client:
        url: http://localhost:8084
