server:
  port: 8040

spring:
  application:
    name: ai-data-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      client:
        url: http://localhost:8084
