server:
  port: 8020
  servlet:
    context-path: /api/user
spring:
  profiles:
    active: dev
  application:
    name: ai-data-processor
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
        namespace: ${NACOS_NAMESPACE}
        group: ${NACOS_GROUP}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER_NAME}
    password: ${RABBIT_MQ_PASSWORD}
    publisher-confirm-type: correlated # 开启发送确认
    publisher-returns: true            # 开启发送失败返回
# ======================================================
jwt:
  secret: ${JWT_SECRET_KEY}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: false
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.yuan.model.entity
  mapper-locations: classpath:mapper/*.xml
